[build]
command = "npm run build"
publish = "dist"

[build.environment]
PUBLIC_SITE_URL = "https://clashpanel.netlify.app"

[[redirects]]
from = "/api/*"
to = "https://clashpanel-api-982136486076.europe-west1.run.app/:splat"
status = 200
force = true