-- Compact achievement catalog and subject state.
-- Legacy achievement_progress and clan_achievement_progress remain available as
-- parity data; this migration only adds the compact representation and backfills it.
-- Base snapshots/source records and their indexes are retained: history reads and
-- incremental-source processing still consume them, so no index is demonstrably
-- redundant from this migration alone.

create table if not exists public.achievement_families (
    family_id smallint generated by default as identity primary key,
    family_key text not null unique,
    scope text not null default 'player' check (scope in ('player', 'clan')),
    category text not null default '',
    metric text not null default '',
    title text not null default '',
    description text not null default '',
    comparison text not null default 'GTE'
        check (comparison in ('GTE', 'LTE', 'BOOLEAN', 'UNSUPPORTED'))
);

create table if not exists public.achievement_definitions (
    achievement_id smallint generated by default as identity primary key,
    family_id smallint not null references public.achievement_families(family_id) on delete cascade,
    achievement_key text not null unique,
    tier smallint not null check (tier > 0),
    target bigint not null check (target > 0),
    xp integer not null default 0 check (xp >= 0),
    rarity text not null default '',
    unique (family_id, tier)
);

create table if not exists public.player_achievement_state (
    user_id uuid not null,
    player_tag text not null check (player_tag ~ '^#[0289PYLQGRJCUV]{3,15}$'),
    family_ids smallint[] not null default '{}'::smallint[],
    progress_values bigint[] not null default '{}'::bigint[],
    source_timestamp bigint not null default 0,
    updated_at timestamptz not null default now(),
    primary key (user_id, player_tag),
    constraint player_achievement_state_parallel_arrays
        check (cardinality(family_ids) = cardinality(progress_values))
);

create table if not exists public.player_achievement_unlocks (
    user_id uuid not null,
    player_tag text not null check (player_tag ~ '^#[0289PYLQGRJCUV]{3,15}$'),
    achievement_id smallint not null references public.achievement_definitions(achievement_id) on delete cascade,
    unlocked_at timestamptz not null default now(),
    primary key (user_id, player_tag, achievement_id)
);

create table if not exists public.clan_achievement_state (
    clan_tag text not null check (clan_tag ~ '^#[0289PYLQGRJCUV]{3,15}$'),
    family_ids smallint[] not null default '{}'::smallint[],
    progress_values bigint[] not null default '{}'::bigint[],
    evidence_timestamp bigint not null default 0,
    evidence_source text not null default '',
    updated_at timestamptz not null default now(),
    primary key (clan_tag),
    constraint clan_achievement_state_parallel_arrays
        check (cardinality(family_ids) = cardinality(progress_values))
);

create table if not exists public.clan_achievement_unlocks (
    clan_tag text not null check (clan_tag ~ '^#[0289PYLQGRJCUV]{3,15}$'),
    achievement_id smallint not null references public.achievement_definitions(achievement_id) on delete cascade,
    unlocked_at timestamptz not null default now(),
    primary key (clan_tag, achievement_id)
);

alter table public.player_achievement_state
    drop constraint if exists player_achievement_state_account_fkey;
alter table public.player_achievement_state
    add constraint player_achievement_state_account_fkey
    foreign key (user_id, player_tag)
    references public.user_accounts(user_id, player_tag) on delete cascade;

alter table public.player_achievement_unlocks
    drop constraint if exists player_achievement_unlocks_account_fkey;
alter table public.player_achievement_unlocks
    add constraint player_achievement_unlocks_account_fkey
    foreign key (user_id, player_tag)
    references public.user_accounts(user_id, player_tag) on delete cascade;

alter table public.achievement_families enable row level security;
alter table public.achievement_definitions enable row level security;
alter table public.player_achievement_state enable row level security;
alter table public.player_achievement_unlocks enable row level security;
alter table public.clan_achievement_state enable row level security;
alter table public.clan_achievement_unlocks enable row level security;

revoke all on table public.achievement_families, public.achievement_definitions,
    public.player_achievement_state, public.player_achievement_unlocks,
    public.clan_achievement_state, public.clan_achievement_unlocks
    from public, anon, authenticated;
grant select, insert, update, delete on table public.achievement_families,
    public.achievement_definitions, public.player_achievement_state,
    public.player_achievement_unlocks, public.clan_achievement_state,
    public.clan_achievement_unlocks to service_role;

-- Populate the global catalog once from both legacy ledgers. Title and
-- description deliberately live on the tier definition because they can vary by
-- tier even when family category and metric are stable.
do $compact$
begin
    if exists (
        select family_key
        from (
            select family_key, 'player'::text as scope from public.achievement_progress
            union all
            select family_key, 'clan'::text from public.clan_achievement_progress
        ) source_rows
        group by family_key
        having count(distinct scope) > 1
    ) then
        raise exception 'Achievement family key cannot mix player and clan scopes';
    end if;
end;
$compact$;

with source_rows as (
    select family_key, category, metric, title, description, tier,
        achievement_key, 'player'::text as scope
    from public.achievement_progress
    union all
    select family_key, category, metric, title, description, tier,
        achievement_key, 'clan'::text
    from public.clan_achievement_progress
), chosen as (
    select distinct on (family_key) family_key, category, metric, title, description, scope,
        case when metric in (
                 'legend_best_season_rank',
                 'ranking_best_global_rank',
                 'base_min_positive_timer_seconds'
             )
             then 'LTE' else 'GTE' end as comparison
    from source_rows
    order by family_key, case when scope = 'player' then 0 else 1 end, tier, achievement_key
)
insert into public.achievement_families
    (family_key, scope, category, metric, title, description, comparison)
select family_key, scope, coalesce(category, ''), coalesce(metric, ''),
    coalesce(title, ''), coalesce(description, ''), comparison
from chosen
where nullif(btrim(family_key), '') is not null
on conflict (family_key) do update
set category = coalesce(nullif(excluded.category, ''), public.achievement_families.category),
    metric = coalesce(nullif(excluded.metric, ''), public.achievement_families.metric),
    title = coalesce(nullif(excluded.title, ''), public.achievement_families.title),
    description = coalesce(nullif(excluded.description, ''), public.achievement_families.description),
    comparison = case when public.achievement_families.comparison = 'GTE'
                      and excluded.comparison = 'LTE' then 'LTE'
                      else public.achievement_families.comparison end;

with source_rows as (
    select achievement_key, family_key, tier, target, xp, title, description,
        rarity, 'GTE'::text as comparison
    from public.achievement_progress
    union all
    select achievement_key, family_key, tier, target, 0, title, description,
        rarity, 'GTE'::text
    from public.clan_achievement_progress
), chosen as (
    -- The legacy table repeats every definition once per player. Pick one
    -- canonical row before the global upsert so one INSERT never updates the
    -- same catalog row twice.
    select distinct on (family_key, tier) achievement_key, family_key, tier, target,
        xp, title, description, rarity
    from source_rows
    order by family_key, tier, xp desc, achievement_key, title, description
)
insert into public.achievement_definitions (
    family_id, achievement_key, tier, target, xp, rarity
)
select f.family_id, s.achievement_key, s.tier, greatest(s.target, 1), greatest(s.xp, 0),
    coalesce(s.rarity, '')
from chosen s
join public.achievement_families f on f.family_key = s.family_key
where nullif(btrim(s.achievement_key), '') is not null
on conflict (achievement_key) do update
set family_id = excluded.family_id,
    tier = excluded.tier,
    target = excluded.target,
    xp = greatest(public.achievement_definitions.xp, excluded.xp),
    rarity = excluded.rarity;

-- Collapse repeated legacy tier rows into one progress value per family.
with grouped as (
    select p.user_id, p.player_tag, f.family_id, f.comparison,
        case when f.comparison = 'LTE'
             then coalesce(min(p.progress) filter (where p.progress > 0), 0)
             else max(p.progress) end as progress,
        max(p.source_timestamp) as source_timestamp
    from public.achievement_progress p
    join public.achievement_families f on f.family_key = p.family_key
    where f.scope = 'player'
    group by p.user_id, p.player_tag, f.family_id, f.comparison
), states as (
    select user_id, player_tag,
        array_agg(family_id order by family_id)::smallint[] as family_ids,
        array_agg(progress order by family_id)::bigint[] as progress_values,
        max(source_timestamp) as source_timestamp
    from grouped
    group by user_id, player_tag
)
insert into public.player_achievement_state
    (user_id, player_tag, family_ids, progress_values, source_timestamp)
select user_id, player_tag, family_ids, progress_values, source_timestamp
from states
on conflict (user_id, player_tag) do update
set family_ids = excluded.family_ids,
    progress_values = excluded.progress_values,
    source_timestamp = greatest(public.player_achievement_state.source_timestamp, excluded.source_timestamp),
    updated_at = now();

with candidates as (
    select p.user_id, p.player_tag, d.achievement_id,
        coalesce(p.unlocked_at, p.updated_at, now()) as unlocked_at,
        row_number() over (
            partition by p.user_id, p.player_tag, d.achievement_id
            order by p.unlocked_at nulls last, p.updated_at
        ) as rank
    from public.achievement_progress p
    join public.achievement_definitions d on d.achievement_key = p.achievement_key
    join public.achievement_families f on f.family_id = d.family_id
    where f.scope = 'player'
      and (p.unlocked
       or (f.comparison = 'GTE' and p.progress >= d.target)
       or (f.comparison = 'LTE' and p.progress > 0 and p.progress <= d.target)
       or (f.comparison = 'BOOLEAN' and p.progress > 0))
)
insert into public.player_achievement_unlocks (user_id, player_tag, achievement_id, unlocked_at)
select user_id, player_tag, achievement_id, unlocked_at
from candidates
where rank = 1
on conflict (user_id, player_tag, achievement_id) do nothing;

with grouped as (
    select p.clan_tag, f.family_id, f.comparison,
        case when f.comparison = 'LTE'
             then coalesce(min(p.progress) filter (where p.progress > 0), 0)
             else max(p.progress) end as progress,
        max(p.evidence_timestamp) as evidence_timestamp,
        (array_agg(p.evidence_source order by p.evidence_timestamp desc))[1] as evidence_source
    from public.clan_achievement_progress p
    join public.achievement_families f on f.family_key = p.family_key
    where f.scope = 'clan'
    group by p.clan_tag, f.family_id, f.comparison
), states as (
    select clan_tag,
        array_agg(family_id order by family_id)::smallint[] as family_ids,
        array_agg(progress order by family_id)::bigint[] as progress_values,
        max(evidence_timestamp) as evidence_timestamp,
        (array_agg(evidence_source order by evidence_timestamp desc, family_id))[1] as evidence_source
    from grouped
    group by clan_tag
)
insert into public.clan_achievement_state
    (clan_tag, family_ids, progress_values, evidence_timestamp, evidence_source)
select clan_tag, family_ids, progress_values, evidence_timestamp, coalesce(evidence_source, '')
from states
on conflict (clan_tag) do update
set family_ids = excluded.family_ids,
    progress_values = excluded.progress_values,
    evidence_timestamp = greatest(public.clan_achievement_state.evidence_timestamp, excluded.evidence_timestamp),
    evidence_source = excluded.evidence_source,
    updated_at = now();

with candidates as (
    select p.clan_tag, d.achievement_id,
        coalesce(p.unlocked_at, p.updated_at, now()) as unlocked_at,
        row_number() over (
            partition by p.clan_tag, d.achievement_id
            order by p.unlocked_at nulls last, p.updated_at
        ) as rank
    from public.clan_achievement_progress p
    join public.achievement_definitions d on d.achievement_key = p.achievement_key
    join public.achievement_families f on f.family_id = d.family_id
    where f.scope = 'clan'
      and (p.unlocked
       or (f.comparison = 'GTE' and p.progress >= d.target)
       or (f.comparison = 'LTE' and p.progress > 0 and p.progress <= d.target)
       or (f.comparison = 'BOOLEAN' and p.progress > 0))
)
insert into public.clan_achievement_unlocks (clan_tag, achievement_id, unlocked_at)
select clan_tag, achievement_id, unlocked_at
from candidates
where rank = 1
on conflict (clan_tag, achievement_id) do nothing;
