-- Advanced achievements foundation.
-- Base payloads are copied manually by the owner from the in-game settings screen.

create table if not exists public.achievement_base_snapshots (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.users(id) on delete cascade,
    player_tag text not null check (player_tag ~ '^#[0289PYLQGRJCUV]{3,15}$'),
    source_timestamp bigint not null,
    imported_at timestamptz not null default now(),
    checksum text not null check (length(checksum) = 64),
    payload jsonb not null,
    metrics jsonb not null default '{}'::jsonb,
    constraint achievement_base_snapshots_unique_source
        unique (user_id, player_tag, source_timestamp)
);

create index if not exists achievement_base_snapshots_player_time_idx
    on public.achievement_base_snapshots (user_id, player_tag, source_timestamp desc);

create table if not exists public.achievement_progress (
    user_id uuid not null references public.users(id) on delete cascade,
    player_tag text not null check (player_tag ~ '^#[0289PYLQGRJCUV]{3,15}$'),
    achievement_key text not null,
    family_key text not null,
    title text not null,
    description text not null,
    category text not null,
    rarity text not null check (rarity in ('common', 'rare', 'epic', 'legendary')),
    tier smallint not null check (tier between 1 and 4),
    xp integer not null check (xp >= 0),
    metric text not null,
    progress bigint not null default 0 check (progress >= 0),
    target bigint not null check (target > 0),
    unlocked boolean not null default false,
    unlocked_at timestamptz,
    source_timestamp bigint not null,
    updated_at timestamptz not null default now(),
    primary key (user_id, player_tag, achievement_key, tier)
);

create index if not exists achievement_progress_player_idx
    on public.achievement_progress (user_id, player_tag, category, family_key, tier);

alter table public.achievement_base_snapshots enable row level security;
alter table public.achievement_progress enable row level security;

revoke all on table public.achievement_base_snapshots from anon, authenticated;
revoke all on table public.achievement_progress from anon, authenticated;

drop function if exists public.save_achievement_import(uuid, text, bigint, text, jsonb, jsonb, jsonb);
create function public.save_achievement_import(
    p_user_id uuid,
    p_player_tag text,
    p_source_timestamp bigint,
    p_checksum text,
    p_payload jsonb,
    p_metrics jsonb,
    p_progress jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_snapshot_id bigint;
    v_item jsonb;
    v_was_unlocked boolean;
    v_new_unlocks integer := 0;
begin
    if p_user_id is null or p_player_tag is null or p_payload is null then
        raise exception 'Missing required achievement import data';
    end if;

    insert into public.achievement_base_snapshots (
        user_id, player_tag, source_timestamp, checksum, payload, metrics
    ) values (
        p_user_id, p_player_tag, p_source_timestamp, p_checksum, p_payload, coalesce(p_metrics, '{}'::jsonb)
    )
    on conflict (user_id, player_tag, source_timestamp) do update
        set checksum = excluded.checksum,
            payload = excluded.payload,
            metrics = excluded.metrics,
            imported_at = now()
    returning id into v_snapshot_id;

    for v_item in
        select value from jsonb_array_elements(coalesce(p_progress, '[]'::jsonb))
    loop
        select unlocked
          into v_was_unlocked
          from public.achievement_progress
         where user_id = p_user_id
           and player_tag = p_player_tag
           and achievement_key = v_item->>'achievement_key'
           and tier = (v_item->>'tier')::smallint;

        if coalesce(v_was_unlocked, false) = false
           and coalesce((v_item->>'unlocked')::boolean, false) = true then
            v_new_unlocks := v_new_unlocks + 1;
        end if;

        insert into public.achievement_progress (
            user_id, player_tag, achievement_key, family_key, title, description,
            category, rarity, tier, xp, metric, progress, target, unlocked,
            unlocked_at, source_timestamp, updated_at
        ) values (
            p_user_id,
            p_player_tag,
            v_item->>'achievement_key',
            v_item->>'family_key',
            v_item->>'title',
            v_item->>'description',
            v_item->>'category',
            v_item->>'rarity',
            (v_item->>'tier')::smallint,
            (v_item->>'xp')::integer,
            v_item->>'metric',
            greatest((v_item->>'progress')::bigint, 0),
            (v_item->>'target')::bigint,
            coalesce((v_item->>'unlocked')::boolean, false),
            case when coalesce((v_item->>'unlocked')::boolean, false) then now() else null end,
            p_source_timestamp,
            now()
        )
        on conflict (user_id, player_tag, achievement_key, tier) do update
            set family_key = excluded.family_key,
                title = excluded.title,
                description = excluded.description,
                category = excluded.category,
                rarity = excluded.rarity,
                xp = excluded.xp,
                metric = excluded.metric,
                progress = greatest(public.achievement_progress.progress, excluded.progress),
                target = excluded.target,
                unlocked = public.achievement_progress.unlocked or excluded.unlocked,
                unlocked_at = case
                    when public.achievement_progress.unlocked_at is not null
                        then public.achievement_progress.unlocked_at
                    when excluded.unlocked
                        then now()
                    else null
                end,
                source_timestamp = greatest(public.achievement_progress.source_timestamp, excluded.source_timestamp),
                updated_at = now();
    end loop;

    return jsonb_build_object(
        'snapshotId', v_snapshot_id,
        'savedAt', now(),
        'newUnlocks', v_new_unlocks
    );
end;
$$;

revoke all on function public.save_achievement_import(uuid, text, bigint, text, jsonb, jsonb, jsonb)
    from public, anon, authenticated;
grant execute on function public.save_achievement_import(uuid, text, bigint, text, jsonb, jsonb, jsonb)
    to service_role;
