import Java.achievements.AchievementDefinition;
import Java.achievements.AchievementSpecV2Bindings;
import Java.achievements.AchievementSpecV2Catalog;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/** Generates the SQL catalog seed from the authoritative embedded v2 catalog. */
public final class GenerateAchievementCatalogSeed {
    private GenerateAchievementCatalogSeed() {}

    public static void main(String[] args) throws Exception {
        if (args.length != 1) {
            throw new IllegalArgumentException("Expected one output migration path");
        }

        JsonArray rows = new JsonArray();
        for (AchievementDefinition definition : AchievementSpecV2Catalog.definitions()) {
            AchievementSpecV2Catalog.Metadata metadata =
                    AchievementSpecV2Catalog.metadata(definition.key());
            JsonObject row = new JsonObject();
            row.addProperty("family_key", definition.familyKey());
            row.addProperty("scope", "clan".equalsIgnoreCase(metadata.scope()) ? "clan" : "player");
            row.addProperty("category", definition.category());
            row.addProperty("metric", definition.metric());
            row.addProperty("comparison", comparison(metadata.comparison()));
            row.addProperty("achievement_key", definition.key());
            row.addProperty("tier", definition.tier());
            row.addProperty("target", definition.target());
            row.addProperty("xp", definition.xp());
            row.addProperty("title", definition.title());
            row.addProperty("description", definition.description());
            row.addProperty("rarity", definition.rarity());
            rows.add(row);
        }

        String sql = migration(rows.toString());
        Files.writeString(Path.of(args[0]), sql, StandardCharsets.UTF_8);
    }

    private static String comparison(AchievementSpecV2Bindings.Comparison comparison) {
        return comparison == null ? "UNSUPPORTED" : comparison.name();
    }

    private static String migration(String catalogJson) {
        return """
                -- Generated by scripts/GenerateAchievementCatalogSeed.java from
                -- AchievementSpecV2Catalog. Do not edit catalog content by hand.

                create temporary table compact_achievement_catalog_seed on commit drop as
                select *
                from jsonb_to_recordset($catalog$%s$catalog$::jsonb) as seed(
                    family_key text, scope text, category text, metric text, comparison text,
                    achievement_key text, tier smallint, target bigint, xp integer,
                    title text, description text, rarity text
                );

                insert into public.achievement_families
                    (family_key, scope, category, metric, title, description, comparison)
                select distinct on (family_key)
                    family_key, scope, category, metric, title, description, comparison
                from compact_achievement_catalog_seed
                order by family_key, tier
                on conflict (family_key) do update
                set scope = excluded.scope,
                    category = excluded.category,
                    metric = excluded.metric,
                    title = excluded.title,
                    description = excluded.description,
                    comparison = excluded.comparison;

                insert into public.achievement_definitions
                    (family_id, achievement_key, tier, target, xp, rarity)
                select f.family_id, s.achievement_key, s.tier, s.target, s.xp, s.rarity
                from compact_achievement_catalog_seed s
                join public.achievement_families f on f.family_key = s.family_key
                order by f.family_id, s.tier
                on conflict (achievement_key) do update
                set family_id = excluded.family_id,
                    tier = excluded.tier,
                    target = excluded.target,
                    xp = excluded.xp,
                    rarity = excluded.rarity;

                do $catalog_parity$
                begin
                    if (select count(distinct family_key) from compact_achievement_catalog_seed) <> 340 then
                        raise exception 'Compact achievement catalog family count mismatch';
                    end if;
                    if (select count(*) from compact_achievement_catalog_seed) <> 1331 then
                        raise exception 'Compact achievement catalog tier count mismatch';
                    end if;
                    if exists (
                        select 1
                        from compact_achievement_catalog_seed s
                        left join public.achievement_families f using (family_key)
                        left join public.achievement_definitions d
                          on d.family_id = f.family_id and d.achievement_key = s.achievement_key
                        where f.family_id is null or d.achievement_id is null
                           or f.comparison <> s.comparison or d.tier <> s.tier
                           or d.target <> s.target or d.xp <> s.xp
                    ) then
                        raise exception 'Compact achievement catalog seed parity failed';
                    end if;
                end;
                $catalog_parity$;

                drop table compact_achievement_catalog_seed;
                """.formatted(catalogJson);
    }
}
