export const APP_ASSETS = new Map([
    ["/dashboard", "/subpages/dashboard"],
    ["/app/explore", "/subpages/explore"],
    ["/app/cwl-planner", "/subpages/cwl-planner"],
    ["/app/cwl-planner-drafts", "/subpages/cwl-planner-drafts"],
    ["/app/cwl-tracker", "/subpages/cwl-operation-board"],
    ["/app/clan-management", "/subpages/groups"],
    ["/app/war-board", "/subpages/war-operation-board"],
    ["/app/brackets", "/subpages/bracket-generator"],
    ["/app/minigames", "/subpages/minigames"],
    ["/app/advanced-stats", "/subpages/advanced-stats"],
    ["/app/achievements", "/subpages/achievements"],
    ["/app/profile", "/subpages/profile"]
]);
export const APP_ALIASES = new Map([
    ["/dashboard.html", "/dashboard"],
    ["/app/dashboard", "/dashboard"],
    ["/app/dashboard.html", "/dashboard"],
    ["/app/explore.html", "/app/explore"],
    ["/app/cwl-planner.html", "/app/cwl-planner"],
    ["/app/cwl-planner-drafts.html", "/app/cwl-planner-drafts"],
    ["/app/cwl-operation-board", "/app/cwl-tracker"],
    ["/app/cwl-operation-board.html", "/app/cwl-tracker"],
    ["/app/cwl-tracker.html", "/app/cwl-tracker"],
    ["/app/groups", "/app/clan-management"],
    ["/app/groups.html", "/app/clan-management"],
    ["/app/clan-management.html", "/app/clan-management"],
    ["/app/war-operation-board", "/app/war-board"],
    ["/app/war-operation-board.html", "/app/war-board"],
    ["/app/war-board.html", "/app/war-board"],
    ["/app/bracket-generator", "/app/brackets"],
    ["/app/bracket-generator.html", "/app/brackets"],
    ["/app/brackets.html", "/app/brackets"],
    ["/app/minigames.html", "/app/minigames"],
    ["/app/achievements", "/dashboard"],
    ["/app/achievements.html", "/dashboard"],
    ["/app/advanced-stats", "/dashboard"],
    ["/app/advanced-stats.html", "/dashboard"],
    ["/app/profile.html", "/app/profile"]
]);
