export const APP_ASSETS = new Map([
    ["/dashboard", "/subPages/dashboard"],
    ["/subpages/login", "/subPages/login"],
    ["/subpages/register", "/subPages/register"],
    ["/app/explore", "/subPages/explore"],
    ["/app/cwl-planner", "/subPages/cwl-planner"],
    ["/app/cwl-planner-drafts", "/subPages/cwl-planner-drafts"],
    ["/app/cwl-tracker", "/subPages/cwl-operation-board"],
    ["/app/clan-management", "/subPages/groups"],
    ["/app/war-board", "/subPages/war-operation-board"],
    ["/app/brackets", "/subPages/bracket-generator"],
    ["/app/minigames", "/subPages/minigames"],
    ["/app/advanced-stats", "/subPages/advanced-stats"],
    ["/app/achievements", "/subPages/achievements"],
    ["/app/profile", "/subPages/profile"]
]);
export const APP_ALIASES = new Map([
    ["/dashboard.html", "/dashboard"],
    ["/subpages/login.html", "/subpages/login"],
    ["/subpages/register.html", "/subpages/register"],
    ["/app/dashboard", "/dashboard"],
    ["/app/dashboard.html", "/dashboard"],
    ["/app/explore.html", "/app/explore"],
    ["/app/cwl-planner.html", "/app/cwl-planner"],
    ["/app/cwl-planner-drafts.html", "/app/cwl-planner-drafts"],
    ["/app/cwl-operation-board", "/app/cwl-tracker"],
    ["/app/cwl-operation-board.html", "/app/cwl-tracker"],
    ["/app/cwl-tracker.html", "/app/cwl-tracker"],
    ["/app/groups", "/app/clan-management"],
    ["/app/groups.html", "/app/clan-management"],
    ["/app/clan-management.html", "/app/clan-management"],
    ["/app/war-operation-board", "/app/war-board"],
    ["/app/war-operation-board.html", "/app/war-board"],
    ["/app/war-board.html", "/app/war-board"],
    ["/app/bracket-generator", "/app/brackets"],
    ["/app/bracket-generator.html", "/app/brackets"],
    ["/app/brackets.html", "/app/brackets"],
    ["/app/minigames.html", "/app/minigames"],
    ["/app/achievements", "/dashboard"],
    ["/app/achievements.html", "/dashboard"],
    ["/app/advanced-stats", "/dashboard"],
    ["/app/advanced-stats.html", "/dashboard"],
    ["/app/profile.html", "/app/profile"]
]);